import type { Metadata } from "next";
import "./globals.css";
import { Inter, Fira_Code } from "next/font/google";
import Head from "next/head";
import Providers from "@/components/providers";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RM",
  description: "Generated by RM",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(123)
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <title>Rice Management App</title>
        <meta
          name="description"
          content="A Rice Management System by Group 4, FPT University"
        />
      </Head>
      <body className={`${inter.variable} ${firaCode.variable} antialiased`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
