import type { Metadata } from "next";
import "./globals.css";
import { Inter, Fira_Code } from "next/font/google";
import Head from "next/head";
import Providers from "@/components/providers";
import HydrateProvider from "@/components/providers/client-provider/hydrate-provider";
import HydrationPrefetchQuery from "@/components/dashboard/hydration-prefetch-query";
import { ApiQuery } from "@/services/query";
import { getMe } from "@/server/actions";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const firaCode = Fira_Code({
  variable: "--font-fira-code",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "RM",
  description: "Generated by RM",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const query = await getMe();
  return (
    <html lang="en" suppressHydrationWarning>
      <Head>
        <title>Rice Management App</title>
        <meta
          name="description"
          content="A Rice Management System by Group 4, FPT University"
        />
      </Head>
      <body className={`${inter.variable} ${firaCode.variable} antialiased`}>
        <Providers>
          <HydrationPrefetchQuery query={ApiQuery.users.getMe()}>
            <HydrateProvider query={query}>{children}</HydrateProvider>
          </HydrationPrefetchQuery>
        </Providers>
      </body>
    </html>
  );
}
