IF NOT EXISTS (
    SELECT 1
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'users' AND COLUMN_NAME = 'status'
)
BEGIN
ALTER TABLE dbo.users ADD status VARCHAR(10) NOT NULL DEFAULT 'ACTIVE';
END
