INSERT INTO categories (
    name,
    description,
    image_url,
    created_at,
    updated_at
)
VALUES
    (N'Gạo ST25',
     N'Gạo ngon nhất thế giới, từng đạt giải quốc tế',
     'https://example.com/gao_st25.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Nàng Thơm Chợ Đào',
     N'Hương thơm đặc trưng, hạt cơm dẻo và mềm',
     'https://example.com/gao_nang_thom_cho_dao.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Tám Xoan Hải Hậu',
     N'Hạt gạo nhỏ, trắng, thơm nhẹ, đặc sản Hải Hậu',
     'https://example.com/gao_tam_xoan.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Séng Cù',
     N'Đặc sản vùng Tây Bắc, hạt to, thơm và đậm đà',
     'https://example.com/gao_seng_cu.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Điện Biên',
     N'Hương vị đậm đà, dẻo, thơm, đặc sản vùng núi',
     'https://example.com/gao_dien_bien.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Lứt Huyết Rồng',
     N'Gạo lứt giàu dinh dưỡng, hạt màu nâu đỏ đậm',
     'https://example.com/gao_huyet_rong.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Nếp Cẩm',
     N'Dùng để nấu xôi, chè; hạt tím đậm, giàu chất xơ',
     'https://example.com/gao_nep_cam.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Nếp Cái Hoa Vàng',
     N'Nấu xôi thơm dẻo, hạt gạo tròn, trắng đục',
     'https://example.com/gao_nep_cai_hoa_vang.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Japonica',
     N'Hạt tròn, dẻo, thường dùng để nấu cơm kiểu Nhật',
     'https://example.com/gao_japonica.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Koshihikari',
     N'Hạt ngắn, mềm, ngọt, rất phổ biến tại Nhật Bản',
     'https://example.com/gao_koshihikari.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Tài Nguyên',
     N'Cơm khô, tơi, thường dùng cho các món chiên, rang',
     'https://example.com/gao_tai_nguyen.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Jasmine',
     N'Hạt dài, thơm nhẹ, mềm và dẻo khi nấu',
     'https://example.com/gao_jasmine.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Hương Lài',
     N'Hạt trắng, thơm tự nhiên, vị ngọt dịu',
     'https://example.com/gao_huong_lai.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Basmati',
     N'Hạt dài, tơi, thường dùng cho ẩm thực Ấn Độ',
     'https://example.com/gao_basmati.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Hạt Ngọc Trời',
     N'Thương hiệu gạo cao cấp, hạt đều và thơm',
     'https://example.com/gao_hat_ngoc_troi.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Hương Quê',
     N'Hạt dẻo thơm, thường dùng trong gia đình Việt',
     'https://example.com/gao_huong_que.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Nếp Nương',
     N'Đặc sản vùng Tây Bắc, dẻo, thơm, nấu xôi rất ngon',
     'https://example.com/gao_nep_nuong.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Nàng Xuân',
     N'Cơm trắng dẻo, vị ngọt nhẹ, phù hợp bữa ăn hằng ngày',
     'https://example.com/gao_nang_xuan.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Thái Hom Mali',
     N'Gạo thơm của Thái Lan, hạt dài, mềm dẻo',
     'https://example.com/gao_thai_hom_mali.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo ST24',
     N'Tiền thân của ST25, hạt dài, cơm dẻo, thơm dịu',
     'https://example.com/gao_st24.jpg',
     GETDATE(),
     GETDATE());
