INSERT INTO categories (
    name,
    description,
    image_url,
    created_at,
    updated_at
)
VALUES
    (N'Gạo ST25',
     N'Gạo ngon nhất thế giới, từng đạt giải quốc tế',
     'https://example.com/gao_st25.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Nàng Thơm Chợ Đào',
     N'Hương thơm đặc trưng, hạt cơm dẻo và mềm',
     'https://example.com/gao_nang_thom_cho_dao.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Tám Xoan Hải Hậu',
     N'Hạt gạo nhỏ, trắng, thơm nhẹ, đặc sản Hải Hậu',
     'https://example.com/gao_tam_xoan.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Séng Cù',
     N'Đặc sản vùng Tây Bắc, hạt to, thơm và đậm đà',
     'https://example.com/gao_seng_cu.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Điện Biên',
     N'Hương vị đậm đà, dẻo, thơm, đặc sản vùng núi',
     'https://example.com/gao_dien_bien.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Lứt Huyết Rồng',
     N'Gạo lứt giàu dinh dưỡng, hạt màu nâu đỏ đậm',
     'https://example.com/gao_huyet_rong.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Nếp Cẩm',
     N'Dùng để nấu xôi, chè; hạt tím đậm, giàu chất xơ',
     'https://example.com/gao_nep_cam.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Nếp Cái Hoa Vàng',
     N'Nấu xôi thơm dẻo, hạt gạo tròn, trắng đục',
     'https://example.com/gao_nep_cai_hoa_vang.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Japonica',
     N'Hạt tròn, dẻo, thường dùng để nấu cơm kiểu Nhật',
     'https://example.com/gao_japonica.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Koshihikari',
     N'Hạt ngắn, mềm, ngọt, rất phổ biến tại Nhật Bản',
     'https://example.com/gao_koshihikari.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Tài Nguyên',
     N'Cơm khô, tơi, thường dùng cho các món chiên, rang',
     'https://example.com/gao_tai_nguyen.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Jasmine',
     N'Hạt dài, thơm nhẹ, mềm và dẻo khi nấu',
     'https://example.com/gao_jasmine.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Hương Lài',
     N'Hạt trắng, thơm tự nhiên, vị ngọt dịu',
     'https://example.com/gao_huong_lai.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Basmati',
     N'Hạt dài, tơi, thường dùng cho ẩm thực Ấn Độ',
     'https://example.com/gao_basmati.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Hạt Ngọc Trời',
     N'Thương hiệu gạo cao cấp, hạt đều và thơm',
     'https://example.com/gao_hat_ngoc_troi.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Hương Quê',
     N'Hạt dẻo thơm, thường dùng trong gia đình Việt',
     'https://example.com/gao_huong_que.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Nếp Nương',
     N'Đặc sản vùng Tây Bắc, dẻo, thơm, nấu xôi rất ngon',
     'https://example.com/gao_nep_nuong.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Nàng Xuân',
     N'Cơm trắng dẻo, vị ngọt nhẹ, phù hợp bữa ăn hằng ngày',
     'https://example.com/gao_nang_xuan.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo Thái Hom Mali',
     N'Gạo thơm của Thái Lan, hạt dài, mềm dẻo',
     'https://example.com/gao_thai_hom_mali.jpg',
     GETDATE(),
     GETDATE()),
    (N'Gạo ST24',
     N'Tiền thân của ST25, hạt dài, cơm dẻo, thơm dịu',
     'https://example.com/gao_st24.jpg',
     GETDATE(),
     GETDATE());

     INSERT INTO suppliers (name, contact_name, phone, email, tax_code, address, website, description) VALUES
(N'Công Ty TNHH An Phát', N'Nguyễn Văn An', N'0901234567', N'an.nguyen@anphat.vn', N'0123456789', N'123 Đường Lê Lợi, Quận 1, TP.HCM', N'http://www.anphat.vn', N'Nhà cung cấp thiết bị văn phòng.'),
(N'Công Ty CP Bình Minh', N'Trần Thị Bình', N'0912345678', N'binh.tran@binhminh.vn', N'9876543210', N'456 Đường Trần Hưng Đạo, Hà Nội', N'http://www.binhminh.vn', N'Chuyên phân phối linh kiện điện tử.'),
(N'Công Ty TNHH Cường Thịnh', N'Lê Văn Cường', N'0923456789', N'cuong.le@cuongthinh.vn', N'1234567890123', N'789 Đường Phạm Văn Đồng, Hải Phòng', N'http://www.cuongthinh.vn', N'Nhà cung cấp vật liệu xây dựng.'),
(N'Công Ty CP Duy Tân', N'Phạm Thị Duyên', N'0934567890', N'duyen.pham@duytan.vn', N'2345678901', N'321 Đường Hai Bà Trưng, Đà Nẵng', N'http://www.duytan.vn', N'Chuyên cung cấp giải pháp CNTT.'),
(N'Công Ty TNHH Ecoline', N'Vũ Minh E', N'0945678901', N'minh.vu@ecoline.vn', N'3456789012', N'654 Đường Nguyễn Trãi, Quận 5, TP.HCM', N'http://www.ecoline.vn', N'Nhà cung cấp sản phẩm xanh và bền vững.'),
(N'Công Ty CP FPT Supply', N'Hoàng Văn F', N'0956789012', N'hoang.hoang@fptsupply.vn', N'4567890123', N'987 Đường Cách Mạng, Hà Nội', N'http://www.fptsupply.vn', N'Chuyên cung cấp giải pháp công nghệ.'),
(N'Công Ty TNHH Gia Phát', N'Phạm Văn Gia', N'0967890123', N'gia.pham@gia-phat.vn', N'5678901234', N'159 Đường Lý Thái Tổ, Quận 3, TP.HCM', N'http://www.gia-phat.vn', N'Nhà cung cấp vật tư kỹ thuật.'),
(N'Công Ty CP Hòa Bình', N'Đặng Thị Hòa', N'0978901234', N'hoa.dang@hoabinh.vn', N'6789012345', N'753 Đường Nguyễn Huệ, TP.HCM', N'http://www.hoabinh.vn', N'Chuyên cung cấp sản phẩm gia dụng.'),
(N'Công Ty TNHH Indochina', N'Phạm Văn Ind', N'0989012345', N'ind.pham@indochina.vn', N'7890123456', N'852 Đường Lê Duẩn, Hà Nội', N'http://www.indochina.vn', N'Nhà cung cấp đồ gia dụng cao cấp.'),
(N'Công Ty CP Nhật Minh', N'Trần Văn Nhật', N'0990123456', N'nhat.tran@nhatminh.vn', N'8901234567', N'963 Đường Nguyễn Văn Cừ, TP.HCM', N'http://www.nhatminh.vn', N'Chuyên nhập khẩu nguyên liệu thực phẩm.'),
(N'Công Ty TNHH Phúc Lộc', N'Lê Thị Phúc', N'0901122334', N'phuc.le@phucloc.vn', N'9012345678', N'147 Đường Phan Chu Trinh, Hà Nội', N'http://www.phucloc.vn', N'Nhà cung cấp hàng gia dụng.'),
(N'Công Ty CP Quang Huy', N'Nguyễn Quang Huy', N'0912233445', N'huy.nguyen@quanghuy.vn', N'0123456789123', N'258 Đường Hùng Vương, Hải Phòng', N'http://www.quanghuy.vn', N'Chuyên cung cấp thiết bị điện tử.'),
(N'Công Ty TNHH Sáng Tạo', N'Trần Sáng Tạo', N'0923344556', N'sang.tran@sangtao.vn', N'1122334455', N'369 Đường Lê Lợi, Đà Nẵng', N'http://www.sangtao.vn', N'Nhà cung cấp giải pháp sáng tạo cho doanh nghiệp.'),
(N'Công Ty CP Tân Phát', N'Phạm Tân Phát', N'0934455667', N'tan.pham@tanphat.vn', N'2233445566', N'471 Đường Cách Mạng Tháng 8, TP.HCM', N'http://www.tanphat.vn', N'Chuyên cung cấp hàng tiêu dùng.'),
(N'Công Ty TNHH Uông Bí', N'Vũ Thị Uông', N'0945566778', N'uong.vu@uongbi.vn', N'3344556677', N'582 Đường Võ Văn Kiệt, Nha Trang', N'http://www.uongbi.vn', N'Nhà cung cấp sản phẩm thủ công mỹ nghệ.'),
(N'Công Ty CP Vĩnh Hưng', N'Đinh Vĩnh Hưng', N'0956677889', N'vinh.dinh@vinhhung.vn', N'4455667788', N'693 Đường Lý Tự Trọng, Hà Nội', N'http://www.vinhhung.vn', N'Chuyên cung cấp hàng may mặc.'),
(N'Công Ty TNHH Xanh Eco', N'Ngô Thị Xanh', N'0967788990', N'xanh.ngo@xanheco.vn', N'5566778899', N'804 Đường Nguyễn Du, TP.HCM', N'http://www.xanheco.vn', N'Nhà cung cấp sản phẩm thân thiện với môi trường.'),
(N'Công Ty CP Yên Nhiên', N'Lê Yên Nhiên', N'0978899001', N'yen.le@yennhien.vn', N'6677889900', N'915 Đường Trần Phú, Hà Nội', N'http://www.yennhien.vn', N'Chuyên cung cấp hàng tiêu dùng đa dạng.'),
(N'Công Ty TNHH ZingTech', N'Hoàng Zing', N'0989900112', N'zing.hoang@zingtech.vn', N'7788990011', N'102 Đường Hai Bà Trưng, Đà Nẵng', N'http://www.zingtech.vn', N'Nhà cung cấp thiết bị công nghệ cao.'),
(N'Công Ty CP Vina Trade', N'Trần Vina', N'0990011223', N'vina.tran@vinatrade.vn', N'8899001122', N'203 Đường Phan Đình Phùng, TP.HCM', N'http://www.vinatrade.vn', N'Chuyên cung cấp giải pháp thương mại.');

